Runs 'store_name' through a translit operation before using it
simplifycom/simplify-opencart-module pull request #16
Opened 2020-08-04 12:10 UTC by OnTapKristjan

The only field used by OpenCart extension, that could fail with non-ascii characters, seems to be `store_name`
This PR will try to turn any such value into ASCII

2020-08-25 13:54 UTC, OnTapKristjan commented
@oconnort can you check or request a review for this please?

2020-08-27 19:37 UTC, BlainMaguire requested changes

2020-08-27 19:37 UTC, BlainMaguire commented on src/upload/catalog/controller/extension/payment/simplifycommerce.php
> +                return $copy;
Since this is just attempting to transliterate to the payment name field in the iframe modal, and that's optional, you can just not set it in the template [here](https://github.com/simplifycom/simplify-opencart-module/blob/64cf241d0d1db88f9802375c7302d51754d71c6d/src/upload/catalog/view/theme/default/template/extension/payment/simplifycommerce.twig#L23) if transliteration is not possible (or results in a falsy value like ```''```) rather than allowing it and risking the payment to fail.

2020-09-01 07:27 UTC, OnTapKristjan commented on src/upload/catalog/controller/extension/payment/simplifycommerce.php
> +		    } else if (function_exists('iconv')) {
Valid point

2020-09-01 07:28 UTC, OnTapKristjan commented on src/upload/catalog/controller/extension/payment/simplifycommerce.php
> +                return $copy;
Valid point

2020-09-01 13:56 UTC, BlainMaguire approved these changes

2020-09-04 11:06 UTC, merged